---
####### Create Base Openshift Manifests
- name: '{{ ansible_name_module }} | role | manifests | stat | find data/install-config.yaml'
  stat:
    path: '{{ dir_artifacts }}/data/install-config.yaml'  
  register: data_install_config_yaml

- name: '{{ ansible_name_module }} | role | manifests | stat | find bak/install-config.yaml'
  stat:
    path: '{{ dir_artifacts }}/bak/install-config.yaml'  
  register: bak_install_config_yaml

- name: '{{ ansible_name_module }} | role | manifests | file | Clean/Purge Old Artifacts' 
  file:
    path: '{{ dir_artifacts }}/data/'
    state: absent
  when:
    - data_install_config_yaml.stat.exists == False

- name: '{{ ansible_name_module }} | role | manifests | file | Create {{ dir_artifacts }}/data' 
  file:
    path: '{{ dir_artifacts }}/data'
    state: directory

- name: '{{ ansible_name_module }} | role | manifests | file | Copy install-config.yaml from backup' 
  copy:
    src: '{{ dir_artifacts }}/bak/install-config.yaml'
    dest: '{{ dir_artifacts }}/data/install-config.yaml'
  when:
    - data_install_config_yaml.stat.exists == False
    - bak_install_config_yaml.stat.exists == True

####### Switch to AWS Commercial Credentials
- name: '{{ ansible_name_module }} | copy | Switch to AWS Commercial Credentials'
  copy:
    src: "{{ dir_artifacts }}/.aws/commercial.credentials"
    dest: "{{ local_home }}/.aws/credentials"

- name: '{{ ansible_name_module }} | role | manifests | shell | openshift-install create manifests' 
  shell: "openshift-install create manifests --dir={{ dir_artifacts }}/data"

####### Switch to AWS GovCloud Credentials
- name: '{{ ansible_name_module }} | copy | Switch to AWS Commercial Credentials'
  copy:
    src: "{{ dir_artifacts }}/.aws/govcloud.credentials"
    dest: "{{ local_home }}/.aws/credentials"
