---
- name: '{{ plugin.name }} | role:{{ plugin.role }} | command:rm.rf | Purge pre-existing {{ plugin.role }} bundles'
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '{{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ openshift.provider }}-{{ openshift_version }}.tar'
    - '{{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ openshift.provider }}-{{ openshift_version }}.tar.sha256'

- name: '{{ plugin.name }} | role:{{ plugin.role }} | command:tar.cvf | Build Artifact Bundle'
  shell:
    cmd: |
      tar -vSc -f {{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ openshift.provider }}-{{ openshift_version }}.tar -C /root platform
  args:
    creates: '{{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ openshift.provider }}-{{ openshift_version }}.tar'
    
# Deactivated sha sum ; need to debug
# name: '{{ plugin.name }} | role:{{ plugin.role }} | command:sha256sum | Write checksum on koffer-bundle.{{ plugin.role }}-{{ openshift.provider }}-{{ openshift_version }}.tar'
# command: 'sha256sum {{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ openshift.provider }}-{{ openshift_version }}.tar'
# args:
#   chdir: '{{ dir.bundle }}'
# register: bundle_sha256
    
# name: '{{ plugin.name }} | role:{{ plugin.role }} | copy:content.bundle_sha | Write SHA256 sum File | {{ bundle_sha256.stdout }}'
# copy:
#   dest: '{{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ openshift.provider }}-{{ openshift_version }}.tar.sha256'
#   content: '{{ bundle_sha256.stdout }}'
#   mode: 0666

# name: '{{ plugin.name }} | role:{{ plugin.role }} | file:directory.mode.0777 | Opem Permissions on Bundle Files'
# file:
#   state: file
#   path: '{{ item }}'
#   mode: 0666
# loop:
#   - "{{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ koffer.date }}.tar"
#   - "{{ dir.bundle }}/koffer-bundle.{{ plugin.role }}-{{ koffer.date }}.tar.sha256"
