---
- name: '{{ plugin.name }} | role:{{ plugin.role }} | get_url:url.dest | Save OpenShift openshift-{{ openshift_version }}-release.txt '
  get_url:
    url: '{{ openshift.release_url }}/{{ openshift_version }}/release.txt'
    dest: '{{ dir.meta }}/openshift-{{ openshift_version }}-release.txt'
    mode: 0666

- name: '{{ plugin.name }} | role:{{ plugin.role }} | get_url:url | Download Red Hat CoreOS Image'
  get_url:
    url: '{{ openshift.rhcos_url }}/{{ item.value.image }}'
    dest: '{{ dir.nginx }}/'
    mode: 0666
  with_dict:
    - "{{ rhcos }}"
  when:
    - item.value.download

- name: '{{ plugin.name }} | role:{{ plugin.role }} | shell:oc.adm.release.mirror | Download OpenShift Release images from quay.io'
  shell: |
    {{ dir.bin }}/oc adm release mirror --insecure=true \
      --registry-config={{ koffer.docker_config }} \
      --to={{ koffer.dest }}/openshift-release-dev \
      --from=quay.io/openshift-release-dev/ocp-release:{{ openshift_version }}-x86_64 \
      --to-release-image={{ koffer.dest }}/openshift-release-dev:{{ openshift_version }}-x86_64
  when:
    - koffer.mirror

# name: '{{ ansible_name_module }} | shell:skopeo.copy | Sync content from quay.io'
# shell: |
#     for i in $(cat /var/lib/koffer/release.list); do \
#       skopeo copy docker://quay.io/$i \
#       docker://localhost:5000/openshift-release-dev/$i ; \
#     done
# when: image_mirror_utility == "skopeo"
